# ignore-paths:
#   - docs
ignore-paths:
  - docs
  - src/chemcoord/__init__.py
  - src/chemcoord/constants.py
pylint:
  disable:
    - redefined-builtin
    - protected-access
python-targets:
  - 2
  - 3
