notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

sudo: required
dist: trusty
group: edge

language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install .
script:
  - pytest
