language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
before_install:
  - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'  -y
  - sudo apt-get update -q
  - sudo apt-get install clang-4.0 lldb-4.0 lld-4.0
install:
  - pip install .
# command to run tests
script: pytest
