sudo: required
dist: trusty
group: edge
language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'  -y
  - sudo apt-get update -q
  - sudo apt-get install clang-4.0 libclang-common-4.0-dev libclang-4.0-dev libclang1-4.0 libllvm4.0 lldb-4.0 llvm-4.0 llvm-4.0-dev llvm-4.0-runtime clang-format-4.0 lldb-4.0-dev lld-4.0 libfuzzer-4.0-dev
  # - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  #   else
  #     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #   fi
  # - bash miniconda.sh -b -p $HOME/miniconda
  # - export PATH="$HOME/miniconda/bin:$PATH"
  # - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # # Useful for debugging any issues with conda
  # - conda info -a
  #
  # # Replace dep1 dep2 ... with your dependencies
  # - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  # - source activate test-environment
  # - conda install pytest
  # - conda install scipy numba numpy
  - pip install .
# command to run tests
script:
  - which python
  - python -c "import chemcoord"
  - pytest
