version: 2.1


shared: &shared
    steps:
      - checkout
# This is necessary because of ABI change
# https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp
      - run:
          name: Install numpy
          command: pip3 install numpy>=1.20.1
      - run:
          name: Install chemcoord
          command: pip3 install --editable .
      - run:
          name: Install pytest
          command: pip3 install pytest pytest-cov
      - run:
          name: Running tests
          command: python3 -m pytest --cov=./src/chemcoord
      - run:
          name: Upload coverage reports to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  sample:
    jobs:
      - py37
      - py38

jobs:
  py37:
    <<: *shared
    docker:
      - image: cimg/python:3.7

  py39:
    <<: *shared
    docker:
      - image: cimg/python:3.8
