package:
    name: chemcoord
    version: {{ GIT_DESCRIBE_TAG|replace("v","") }}

source:
    git_url: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas
    - numba
    - sortedcontainers
    - sympy

  run:
    - python
    - numpy
    - scipy
    - pandas
    - numba
    - sortedcontainers
    - sympy

about:
  home: http://chemcoord.readthedocs.io/
  license: LGPLv3
  license_file: LICENSE.md
