package:
    name: chemcoord
    version: {{ GIT_DESCRIBE_TAG|replace("v","") }}

build:
    number: {{ GIT_DESCRIBE_NUMBER|int }}
    # {% if GIT_DESCRIBE_NUMBER|int == 0 %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_0
    # {% else %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}{% endif %}

source:
    git_url: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas
    - numba
    - sortedcontainers
    - sympy

  run:
    - python
    - numpy
    - scipy
    - pandas
    - numba
    - sortedcontainers
    - sympy

test:
  imports:
    - chemcoord

about:
  home: http://chemcoord.readthedocs.io/en/
  license: LGPLv3
  license_file: LICENSE.md
